mysql:
  host: "95.216.5.252"
  port: 3306
  database: "mc_koding"
  username: "mc_koding"
  password: "mc_koding"

discord:
  webhooks:
    ban: "https://discord.com/api/webhooks/..."
    tempban: "https://discord.com/api/webhooks/..."
    unban: "https://discord.com/api/webhooks/..."
    noperms: "https://discord.com/api/webhooks/..."