mysql:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "bruker"
  password: "passord"

discord:
  webhooks:
    ban: "https://discord.com/api/webhooks/..."
    tempban: "https://discord.com/api/webhooks/..."
    unban: "https://discord.com/api/webhooks/..."
    noperms: "https://discord.com/api/webhooks/..."